# Generated by Django 4.2.14 on 2024-07-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
